Add 1.2.1 version (#4)
* Update to passenger 6.0.7

* Update to Alpine 3.12 and drop bzr

* Alpine 3.13

* Use sha256 for checksumming

md5 is insecure, and for the latest releases only .sha256 files are
provided on redmine.org, thus the update.sh fails when downloading .md5
files.

* Refactor Alpine "scanelf" to use similar "ldd" to Debian to avoid new errors in 4.1.2

```
+ apk add --no-network --virtual .redmine-rundeps so:libc.musl-x86_64.so.1 so:libc.so.6 so:libdl.so.2 so:libm.so.6 so:libmariadb.so.3 so:libpq.so.5 so:libpthread.so.0 so:libsqlite3.so.0 so:libsybdb.so.5
WARNING: Ignoring https://dl-cdn.alpinelinux.org/alpine/v3.13/main: No such file or directory
WARNING: Ignoring https://dl-cdn.alpinelinux.org/alpine/v3.13/community: No such file or directory
ERROR: unable to select packages:
  so:libc.so.6 (no such package):
    required by: .redmine-rundeps-20210322.211811[so:libc.so.6]
  so:libdl.so.2 (no such package):
    required by: .redmine-rundeps-20210322.211811[so:libdl.so.2]
  so:libm.so.6 (no such package):
    required by: .redmine-rundeps-20210322.211811[so:libm.so.6]
  so:libpthread.so.0 (no such package):
    required by: .redmine-rundeps-20210322.211811[so:libpthread.so.0]
```

* Update to 4.1.2

* Update to 4.0.8

* Revert "Refactor Alpine "scanelf" to use similar "ldd" to Debian to avoid new errors in 4.1.2"

This reverts commit f35a8c1c9368bf3306b2dc33d7f14531c7f28273.

* Avoid glibc dependency

* Add RedMica 1.2.1

* Update Dockerfile-alpine.template

Co-authored-by: Tianon Gravi <admwiggin@gmail.com>

* Run update.sh

* download shared-mime-info db

* one Gemfile.lock for all adapters

* document database.yml trick

Co-authored-by: Tianon Gravi <admwiggin@gmail.com>

* Update to passenger 6.0.8

* install --without is deprecated

* v4.2.0

* Alpine: download shared-mime-info db

Co-authored-by: Docker Library Bot <github+dockerlibrarybot@infosiftr.com>
Co-authored-by: J0WI <J0WI@users.noreply.github.com>
Co-authored-by: Tianon Gravi <admwiggin@gmail.com>
Co-authored-by: pcworld <0188801@gmail.com>
Co-authored-by: Cyril Jouve <jv.cyril@gmail.com>
Co-authored-by: yosifkit <joe@infosiftr.com>